# Generated by Django 3.0.6 on 2020-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(default='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
